#Default Profile
logging.level:
  org.hibernate: INFO  
  org.springframework: ERROR
  org.springframework.boot.context.embedded: INFO
  com.bank: info

#Setting Profile local/dev/cloud
spring.profiles.active: local

server.servlet.context-path: /bank-${spring.profiles.active}
spring.application.name: Bank Customer Service App - ${spring.profiles.active}

---
#Local Profile
server.port: 8000
spring:
  profiles: local
  h2:
    server.port: 9000
    console.enabled: true
  jpa:
    generate-ddl: true
    show-sql: true    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create
  datasource:
    url: jdbc:h2:mem:bcs-db-${spring.profiles.active};DB_CLOSE_ON_EXIT=FALSE  
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    platform: h2